server:
  port: 8082

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

instance:
  instance-id: service-hi

prefer-ip-address: true

info:
  app.name: oz-microservice-client-demo
  company.name: http://www.gem-soft.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$