#Eureka\u670D\u52A1\u7BA1\u7406\u5668\u5C5E\u6027\u914D\u7F6E\u6587\u4EF6
#\u76D1\u542C\u7AEF\u53E3
server:
  port: 8080
  enable-self-preservation: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server